### PR TITLE
fix: use client/server createHead

### LINKED ISSUE #441: handling of SSR with unhead
Hi @userquin, I was reviewing last update you just merged and seems like we are not  properly handling the unhead on SSR.
https://github.com/antfu-collective/vite-ssg/blob/aaf807e14773fd300f65a05a0e290f91a7a76df1/src/client/index.ts#L37

as per documentation, there should be separate createhead for server and one for client;

https://unhead.unjs.io/docs/typescript/head/guides/get-started/migration#client-server-subpath-exports

So according to that the above line should be replaced with smth like this

```
import { createHead } from '@unhead/vue/client'
import { createHead as createHeadServer } from '@unhead/vue/server'
...
   const head = client ?
        createHead() :
        createHeadServer();
```

Or am I  missing something?

PS. updated code, should have been `client`, not `isClient`

### PR DESCRIPTION
**Pull request by userquin**
### Description

Check linked issue

### Linked Issues

closes #441

### CODE REVIEW

**Comment by userquin** [comment]
Don't merge yet, I'm checking if the server side being removed in the build

**Comment by kevinmarrec** [comment]
I think it's going to have bundle size issues, it's gonna bundle both composables even in client :/

**Comment by kevinmarrec** [comment]
From my experience it can only be dropped with either `import.meta.env.SSR` check (which drops code in the if) or dynamic import (which will cause a new chunk to be created).

I may be wrong

**Comment by userquin** [comment]
We have unhead server in the client build

**Comment by userquin** [comment]
I need to use `process.env.VITE_SSG` and provide it to the vite options via `define` iirc

**Comment by kevinmarrec** [comment]
@userquin If a `define` variable is set to false and used in a condition (if) it automatically drops code ?

I don't know how work ouf of the box `process.env.SSR` with this behavior but I guess it's a built-in `define` ?

**Comment by userquin** [comment]
We cannot, there is only 1 vite build, that's, the build for the app and we're bundling that app build, check L92 in build-ts module => we don't build the client via vite, maybe we need another build for client side

**Comment by userquin** [comment]
I'm going to add `import.meta.env.SSR` or just use `process.env.VITE_SSG` and remove the client/isClient logic using 2 builds, one for SSG and one for the client: I need to replace current entry point injection with the new client entry point.

**Comment by kevinmarrec** [comment]
@userquin I already see one build for client, and one for server (ssg), am I missing someting already ?

**Comment by kevinmarrec** [comment]
https://github.com/antfu-collective/vite-ssg/blob/main/src/node/build.ts#L68 (Client)
https://github.com/antfu-collective/vite-ssg/blob/main/src/node/build.ts#L92 (Server)

**Comment by userquin** [comment]
upps, you're right, it is already there, nice

**Comment by userquin** [comment]
I'm going to fix this, but we will need another breaking change, moving some ssg client configuration to the server ssg options, like unhead and hydration. Why we should allow change using `unhead` or `hydration` at runtime?

The idea is to expose some`import.meta.env` props to allow tree-shake the client code, check last commit.

File: src/client/index.ts [hunk 1]
```diff
@@ -24,26 +24,28 @@ export function ViteSSG(
...
     hydration = false,
   } = options
-  const isClient = typeof window !== 'undefined'
+  const isClient = !!import.meta.env.SSR
 
   async function createApp(client = false, routePath?: string) {
-    const app = client && !hydration
-      ? createClientApp(App)
-      : createSSRApp(App)
+    const app = import.meta.env.SSR
```
Comment (userquin) [inline src/client/index.ts:30]: uhmm

Comment (userquin) [reply src/client/index.ts:30]: ok, it is fine, once the client is built then the code is the same, but how about `unhead` with `client && !hydration`?

File: src/client/single-page.ts [hunk 2]
```diff
@@ -21,22 +22,28 @@ export function ViteSSG(
...
 
   async function createApp(client = false) {
-    const app = client && !hydration
-      ? createClientApp(App)
-      : createSSRApp(App)
+    const app = import.meta.env.SSR
+      ? createSSRApp(App)
+      : client && !hydration
+        ? createClientApp(App)
+        : createSSRApp(App)
```
Comment (userquin) [inline src/client/single-page.ts:32]: check/change also this

File: src/node/build.ts [hunk 3]
```diff
@@ -76,6 +76,9 @@ export async function build(ssgOptions: Partial<ViteSSGOptions> = {}, viteConfig
       },
     },
     mode: config.mode,
+    define: {
+      'import.meta.env.SSR': JSON.stringify(undefined),
```
Comment (userquin) [inline src/node/build.ts:80]: we should check also old Vite versions, and augment vite import meta at least here (or use `process.env.VITE_SSG`)

**Comment by userquin** [comment]
@husayt can you test your app with this PR?

**Comment by husayt** [comment]
Thanks @userquin . I will do that shortly in half hour, and I will let you know

**Comment by userquin** [comment]
> @userquin If a `define` variable is set to false and used in a condition (if) it automatically drops code ?
>

No, just if not defined

> I don't know how work ouf of the box `process.env.SSR` with this behavior but I guess it's a built-in `define` ?
>

You can use variable, the problem is about vite, you need to use import.meta or any env stattibg with VITE_ (`process.env.VITE_`) since Vite will only expose those in the env.

The tree-dhaking is done by rollup.

> EDIT : And I guess that build tools is smart enough to drops `if (false)` blocks

Yes, but in this case we're using vite and rollup

**Comment by husayt** [comment]
I tried latest and I get this error now:

```
/node_modules/.pnpm/vite-ssg@26.0.0_prettier@3.5.3_unhead@2.0.2_vite@6.2.3_@types+node@22.13.14_jiti@2.4.2_terser_6dg3iwks6capxl2h2upvehaajy/node_modules/vite-ssg/dist/index.mjs:16
  const isClient = !!import.meta.env.SSR;
                                     ^

TypeError: Cannot read properties of undefined (reading 'SSR')
    at ViteSSG (/node_modules/.pnpm/vite-ssg@26.0.0_prettier@3.5.3_unhead@2.0.2_vite@6.2.3_@types+node@22.13.14_jiti@2.4.2_terser_6dg3iwks6capxl2h2upvehaajy/node_modules/vite-ssg/dist/index.mjs:16:38)
    at file:///.../.vite-ssg-temp/fxcf3908l3/main.mjs:8134:19
    at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:547:26)
    at async build (/node_modules/.pnpm/vite-ssg@26.0.0_prettier@3.5.3_unhead@2.0.2_vite@6.2.3_@types+node@22.13.14_jiti@2.4.2_terser_6dg3iwks6capxl2h2upvehaajy/node_modules/vite-ssg/dist/shared/vite-ssg.Dd7E8cUf.mjs:1066:87)
    at async CAC.<anonymous> (/node_modules/.pnpm/vite-ssg@26.0.0_prettier@3.5.3_unhead@2.0.2_vite@6.2.3_@types+node@22.13.14_jiti@2.4.2_terser_6dg3iwks6capxl2h2upvehaajy/node_modules/vite-ssg/dist/node/cli.mjs:22:3)
```

**Comment by kevinmarrec** [comment]
I think it requires `vite-ssg` to be in `ssr.noExternal` vite options to prevent @husayt issue, it's because by default `import.meta.env` aren't replaced in `node_modules` without giving hints to Vite

File: src/client/index.ts (hunk 1 above)
Comment (userquin) [reply src/client/index.ts:30]: useHead is agnostic

**Comment by userquin** [comment]
I gess the problem is building the package, we need to prevent rollup tree-shaking the client package (via unbuild), the tests pass here since we're using a stub and the import.meta logic present in the code (I will run the examples usung the dist folder instead the stub).

I'm going to use another approach via virtual module to expose createHead for client and server, vite should work.

For example, nuxt client build using define for import.meta stuff: https://github.com/nuxt/nuxt/blob/5a8a6924d895b4f53f9d59edcffed7e2bf09cabd/packages/vite/src/client.ts#L62

**Comment by userquin** [comment]
@husayt can you test again? using `process.env.VITE_SSG` seems to be working (with tree-shaking => from 269KB to 106KB):

imagen

**Comment by userquin** [comment]
Checkout the branch and run `pnpm install --frozen-lockfile && pnpm build && pnpm pack`, then copy/paste the vite-ssg tgz at root and install it using file protocol in your app (I don't have access to gh setting here to install pkg-pr-new app).

Run `pnpm remove -D vite-ssg && pnpm add -D ./<vite-ssg>.tgz` in a new branch in your repository (or via npm/yarn).

I'm going to prepare a pr to add pkg-pr-new worklow, @antfu should install the app here

**Comment by kevinmarrec** [comment]
@userquin If i'm correct we can drop `client` boolean from `createApp`, as `creteApp` is only called with `false` after `process.env.VITE_SSG` has been set to `true`.

https://github.com/antfu-collective/vite-ssg/blob/97e3361796df34610864d73bfcb93acc317df759/src/node/build.ts#L93
https://github.com/antfu-collective/vite-ssg/blob/97e3361796df34610864d73bfcb93acc317df759/src/node/build.ts#L135
https://github.com/antfu-collective/vite-ssg/blob/97e3361796df34610864d73bfcb93acc317df759/src/node/build.ts#L171

**Comment by userquin** [comment]
Yeah, it is redundant.

We should review the logic since we need to move some runtime stuff to build time (useHead and hydration flags should be moved from ssg client to server options), now when building the client and server app entry points, both will have only the corresponding logic (on client build the server stuff will be tree-shaked and viceversa).

Check https://github.com/antfu-collective/vite-ssg/pull/442#issuecomment-2759396698

**Comment by kevinmarrec** [comment]
Great, I'm gonna try to follow your instructions, I'm using `bun` with a monorepo in my project so it may not be as simple but as soon I'm able to get a `.tgz` with `pnpm` from `vite-ssg` project I should be fine

**Comment by kevinmarrec** [comment]
@userquin Okay, I got a try !

`dev` ❌

image

Error: `Uncaught ReferenceError: process is not defined`

`build` (using `vite`, not `vite-ssg`, stil using `vite-ssg` client side) ✅
image

`build` (using `vite-ssg` the classic way) ✅
image

I'm gonna check bundle sizes diff now

**Comment by kevinmarrec** [comment]
# Bundle size diff

## `vite-ssg@26.0.0`
image

## `vitessg@26.0.0/userquin/fix-handle-ssr`
image

Looks great so far, I think it's not relevant to find out the "why" between `vite build` & `vite-ssg build` differences, as when using `vite-ssg` we should use `vite-ssg build` anyway.

**Comment by userquin** [comment]
arggg, dev will not work since it is just Vite, checking dev env...

**Comment by kevinmarrec** [comment]
@userquin I'm gonna try `node_modules` patches locally to see If I can help you on this

**Comment by husayt** [comment]
Hi again @userquin @kevinmarrec ,

I tried the latest and this time build is working.

But I have some other differences and the key one of them is that in the output.html `window.__INITIAL_STATE__={}` whereas before it had my state

**Comment by userquin** [comment]
The problem now is about importing the corresponding createHead since we cannot use the client in the server entry point and cannot be imported via static import, will fail since there are a few document/window usages, using dynamic import should work but the server stuff will be there

**Comment by kevinmarrec** [comment]
@userquin Replacing `process.env` by `import.meta.env` in `client/index.ts` (or `client/single-page.ts`) fixes `dev` mode, but then break `build`.

**Comment by userquin** [comment]
Using dynamic import:

imagen

**Comment by userquin** [comment]
> @userquin Replacing `process.env` by `import.meta.env` in `client/index.ts` (or `client/single-page.ts`) fixes `dev` mode, but then break `build`.

Yeah, that's what I mean about using Vite in dev, we'll need a dev module for vite-ssg and use it

**Comment by kevinmarrec** [comment]
@userquin I don't like dynamic imports in this context as it enforces new chunk in userland :(

**Comment by userquin** [comment]
Then there is no solution... the virtual approach won't work since we'll need the plugin also in dev (when running v`ite dev` => maybe force adding it from user land adding a new subpackage export.

**Comment by kevinmarrec** [comment]
> The problem now is about importing the corresponding createHead since we cannot use the client in the server entry point and cannot be imported via static import, will fail since there are a few document/window usages, using dynamic import should work but the server stuff will be there

I'm not sure to understand, if conditional block is tree-shaken with `define` technique, imports are supposed to be dropped and not cause any issue.

With current state we identified 2 problem to fix :
- Dev mode
- SSR Initial State (based on @husayt comment)

**Comment by userquin** [comment]
> I'm not sure to understand, if conditional block is tree-shaken with `define` technique, imports are supposed to be dropped and not cause any issue.

There should be some wrong `if` with `proccess.env.VITE_SGG`

> With current state we identified 2 problem to fix :
> 
>     * Dev mode
> 
>     * SSR Initial State (based on @husayt comment)

**Dev mode**: with or without tree-shaking, dev mode can be solved using a virtual + exporting virtual `unhead` plugin + adding the plugin in dev mode

**SSR Initial State (based on @husayt comment)**: whould be fine using virtual approach since we only inject the corresponding client/server  `createHead` module

**Comment by kevinmarrec** [comment]
@userquin I think I made it working :

- Replace `process.env.VITE_SSG` by `import.meta.env.SSR` everywhere
- Drop `client` boolean (only relay on `import.meta.env.SSR`)
- Add `vite-ssg` to `ssr.noExternal` vite options when builiding for ssr (second build in `node/build.ts`

**Comment by userquin** [comment]
checking using `import.meta.env.SSR`...

**Comment by kevinmarrec** [comment]
The only issue is the `hydration check` that will still make both `create` unhead functions to be shipped in client.

**Comment by kevinmarrec** [comment]
@userquin The game changer is `ssr.noExternal`, because if not given it will consider `vite-ssg` import from the ssr entry as external, therefore not tree-shaken :)

**Comment by kevinmarrec** [comment]
I have some packages in my project that relay on `import.meta.env.SSR`, and I never found the problem until I shipped the package and faced `Cannot read properties of undefined (reading 'SSR'` when **installing** it.

Indeed it's considered as external by default when imported from `node_modules`, therefore skipped by Vite for replacements ^^

**Comment by kevinmarrec** [comment]
@userquin 

```ts
const app = import.meta.env.SSR ? createSSRApp(App) : createApp(App)
```

VS

```ts
const app = import.meta.env.SSR || hydration ? createSSRApp(App) : createApp(App)
```

is 5Kb diff

**Comment by userquin** [comment]
can you check with this PR https://github.com/antfu-collective/vite-ssg/pull/444?

File: src/client/index.ts [hunk 4]
```diff
@@ -23,22 +24,32 @@ export function ViteSSG(
     rootContainer = '#app',
     hydration = false,
   } = options
-  const isClient = typeof window !== 'undefined'
+  // eslint-disable-next-line node/prefer-global/process
+  const isClient = !!process.env.VITE_SSG
```
Comment (userquin) [inline src/client/index.ts:28]: this is wrong

**Comment by kevinmarrec** [comment]
> can you check with this PR #444?
> 
> EDIT: working also in dev and tree-shaking server stuff without any external (with the examples here).

Having a try but I think it's missing some pieces, also we should drop `client` boolean as it's only used by ViteSSG to force createApp to be `ssr` oriented. But as `createApp` is imported from ssrEntry it should already be `ssr` tree-shaken

**Comment by userquin** [comment]
updating #444 ...

**Comment by husayt** [comment]
>also we should drop `client` boolean as it's only used by ViteSSG to force createApp to be `ssr` oriented. 

Yes, that was the other thing I noticed not working, so I switched to `import.meta.env.SSR`

File: src/client/index.ts [hunk 5]
```diff
@@ -23,24 +24,27 @@ export function ViteSSG(
...
     hydration = false,
   } = options
-  const isClient = typeof window !== 'undefined'
 
-  async function createApp(client = false, routePath?: string) {
-    const app = client && !hydration
-      ? createClientApp(App)
-      : createSSRApp(App)
+  async function createApp(_client = false, routePath?: string) {
+    const app = import.meta.env.SSR || hydration
```
Comment (userquin) [inline src/client/index.ts:29]: maybe we should add a warning here if calling `createApp(false)` with `!import.meta.env.SSR` (some for spa)

**Comment by userquin** [comment]
We'll need to check changes here with CJS :man_facepalming: :fingers_crossed:

File: src/client/index.ts [hunk 6]
```diff
@@ -23,24 +24,27 @@ export function ViteSSG(
...
 
     if (useHead) {
-      head = createHead()
-      app.use(head)
+      if (import.meta.env.SSR) {
+        app.use(head = createSSRHead())
+      }
+      else {
+        app.use(head = createHead())
+      }
```
Comment (kevinmarrec) [inline src/client/index.ts:41]:
```suggestion
      app.use(head = import.meta.env.SSR ? createSSRHead() : createHead())
```
may just work

**Comment by kevinmarrec** [comment]
[29fedad](https://github.com/antfu-collective/vite-ssg/pull/442/commits/29fedadc4b4869d43f231d06b10a5b3cb40ded84) ✅

Having a last try with the last 2 commits

**Comment by kevinmarrec** [comment]
[31fa5a9](https://github.com/antfu-collective/vite-ssg/pull/442/commits/31fa5a989e35dc111e3c1ecacad86296f15cb35d) ✅

File: src/client/index.ts (hunk 5 above)
Comment (kevinmarrec) [reply src/client/index.ts:29]: This or adding more context in release notes about misusage, as it should not make sense to call `createApp` with `client: false` in a non-client context

**Comment by kevinmarrec** [comment]
I'm using 22.14 on my side, also I have esm only projects so I haven't be able to have a try with cjs

**Comment by userquin** [comment]
> I'm using 22.14 on my side, also I have esm only projects so I haven't be able to have a try with cjs

just change `format: 'cjs'` in the ssg options...

**Comment by kevinmarrec** [comment]
@userquin Anyway `@unhead/vue@2` is ESM only

**Comment by kevinmarrec** [comment]
image

**Comment by userquin** [comment]
@kevinmarrec we should remove format from the SSG options in the new breaking

**Comment by userquin** [comment]
IIRC you need to enable some experimental flag (I don't remember the name, run node --help and check expermiental entries), it is a problem with the Node version where you cannot mix import and require, latest node 22 and node 23 will enable that flag and so we can require and ESM module or import a CJS module

**Comment by kevinmarrec** [comment]
`v26.0.0` is then most probably already breaking people with old Node version, maybe we can update the release note to give a hint, idk.

**Comment by userquin** [comment]
iirc Node 18 will be deprecated next month, and this will break only when using cjs format (unhead is ESM-only)

**Comment by userquin** [comment]
use `feat!: move to ESM-only`  in the new PR title

**Comment by kevinmarrec** [comment]
Yeah, so we turn the whole `vite-ssg` package ESM-only I guess ? Anyway the ecosystem is going this way

**Comment by userquin** [comment]
Yes (right now vite.ssg using dual ESM/CJS without type in the package.json), all Anthony's ecosystem is moving to ESM-only, some packages will require dual ESM/CJS...

**Comment by userquin** [comment]
@husayt did you check your app with latest changes?

**Comment by husayt** [comment]
Yes, latest build went really smooth. Excellent. Thank you very much guys

**Comment by userquin** [comment]
@husayt you can also check your app with #445 (includes the changes in this PR)

**Review by antfu — APPROVED** [review]

**Comment by husayt** [comment]
@userquin @kevinmarrec i am using latest and all is working fine.

But when I run PageSpeed (LightHouse) I get much higher Blocking Time and CLS values than before. I am not sure if this is caused by pagespeed anomaly or due to hydration in new version of vite SSG

image

**Comment by userquin** [comment]
are you using hydration flag when calling ViteSSG? the logic didn't change, only added three-shaking capabilities to remove vue and unhead server logic, I'm going to check what's happening

**Comment by husayt** [comment]
@userquin there is something more serious.  Now all requests they revert to root. When I call subpath let's `/en` it ends up going to root `/`

**Comment by husayt** [comment]
@userquin @kevinmarrec  I just compared to version before vite-ssg 26, this issue with rerouting to route was not there. Seems like major regression where routing is affected.

**Comment by userquin** [comment]
I'm checking what's the problem, I'm figuring out what's the issue

**Comment by kevinmarrec** [comment]
@userquin I don't have much time but I found the issue I let you fix it : client/index.ts line 92 or 93 wrong if check

**Comment by userquin** [comment]
arrgggggggggg
